#spring:
#  cloud:
#    discovery:
#      enabled: true
#  application:
#    name: AUTH-SERVICE
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings.trace: false
#      settings.web-allow-others: false
#
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driver-class-name: org.h2.Driver
#
#logging:
#  level.*:
#    org.springframework.web.client.RestTemplate: INFO
#    com.application.document: DEBUG
#    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: TRACE
#  file:
#    name: logs/auth-app.log
#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/
#
#
#server:
#  port: 9898

server:
  port: 9898
  servlet:
    context-path: /users

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true

spring:

  application.name: authentication
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://127.0.0.1:9411/
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/authentication
    username: root
    password: pass
    hikari:
      auto_commit: false
      driver-class-name: com.mysql.cj.jdbc.Driver
  #  jackson:
  #    deserialization:
  #      FAIL_ON_IGNORED_PROPERTIES: false
  #    serialization:
  #      INDENT_OUTPUT: false
  #      WRITE_DATES_AS_TIMESTAMPS: false
  #      WRITE_BIGDECIMAL_AS_PLAIN: true
  cloud:
    stream:
      binder:
        brokers: localhost:9092
    compatibility-verifier:
      enabled: false

#  file:
#    name: logs/authentication-app.log


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method

