spring:
 cloud:
   discovery:
     enabled: true
   gateway:
     routes:
       - id: swiggy-app
         uri: lb://SWIGGY-APP
         predicates:
           - Path=/swiggy/**
         filters:
           - AuthenticationFilter


       - id: auth-service
         uri: lb://AUTH-SERVICE
         predicates:
           - Path=/summary/**
         filters:
           - AuthenticationFilter

       - id: auth-service
         uri: lb://AUTH-SERVICE
         predicates:
           - Path=/auth/**

 application:
   name: GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/