server:
  port: 8080

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  application.name: gateway-app
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: authentication-token
          uri: lb://authentication
          predicates:
            Path=/users/token/**
          filters:
            - AuthFilter
        - id: authentications
          uri: lb://authentication
          predicates:
            - Path=/users/auth/login,/users/auth/register
        - id: social-api
          uri: lb://SOCIAL-API
          filters:
            - AuthFilter
          predicates:
            - Path=/social/**
  zipkin:
    baseUrl: http://127.0.0.1:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka