spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: DOCUMENTS-SERVICE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/document
    username: root
    password: pass
    hikari:
      auto_commit: false
      driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
  cloud:
    stream:
      binder:
        brokers: localhost:9092
    compatibility-verifier:
      enabled: false

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://127.0.0.1:9411/


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level.*:
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: INFO
    com.food.recipe.api: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: TRACE
  file:
    name: logs/documents-app.log

server:
  port: 9545

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true
