spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: COUNTRY-API
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/countries_api
    username: root
    password: pass
    hikari:
      auto_commit: false
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
  cloud:
    stream:
      binder:
        brokers: localhost:9092
    compatibility-verifier:
      enabled: false
logging:
  level.*:
    org.springframework.web.client.RestTemplate: INFO
    com.com.countries_api: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: TRACE

  file:
    name: logs/countries-api.log

server:
  port: 9972


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
