server.port: 8761
spring:
  application:
    name: EUREKA
  zipkin:
    baseUrl: http://127.0.0.1:9411/
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
