spring:
  aop:
    auto: true
    proxy-target-class: true
  application:
    name: LOGGER-SERVICE
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/logger
    driverClassName: org.postgresql.Driver
    username: postgres
    password: pass
    hikari:
      auto_commit: false
  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
  cloud:
    stream:
      binder:
        brokers: localhost:9092
    compatibility-verifier:
      enabled: false

  zipkin:
    baseUrl: http://127.0.0.1:9411/


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level.*:
    org.springframework.web.client.RestTemplate: INFO
    com.food.recipe.api: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: TRACE
  file:
    name: logs/logger-app.log

server:
  port: 9818